---
# First PlayBook 
# My First Play
- hosts: web
  #sudo: yes 
  tasks:
  - name: Install Apache Packages
    apt: name=apache2 state=present 

  - name: Start Apache Service 
    service: name=apache2 state=started enabled=True 





# My Second Play
- hosts: all
  #sudo: yes 
  tasks:
  - name: Disable FirewallService 
    service: name=ufw state=stopped enabled=False



# My Third Play
- hosts: 'prod:&web:!ansible'
  #sudo: yes 
  tasks:
  - name: Install Tree Packages
    apt: name=tree state=present 

  - name: Start Apache Service 
    service: name=apache2 state=started enabled=True 

