# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  # Master Server
  config.vm.define "tower" do |tower|
    tower.vm.box = "centos/8"
    tower.vm.hostname = "tower.example.com"
    tower.vm.network "private_network", ip: "172.31.0.201"
    tower.vm.provider "virtualbox" do |v|
      v.name = "tower"
      v.memory = 4048
      v.cpus = 2
      # Prevent VirtualBox from interfering with host audio stack
      v.customize ["modifyvm", :id, "--audio", "none"]
    end
  end

end
