---

- hosts: "172.31.0.200"
  name: "Add Common Functional Users"
  vars:
    manala_motd_template: "template/dragon.j2"
    manala_motd_message: "Hey Dragon..!!"
  roles:
  - server-common
  - manala.motd
