---
- hosts: web
  tasks:
  - name: Install HTTPD Packages 
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat" 

  - name: Install Apache Packages
    apt: name=apache2 state=present 
    when: ansible_os_family == "Debian" 

  - name: Start Apache Service 
    service: name=apache2 state=started enabled=True 
    when: ansible_os_family == "Debian" 

  - name: Start HTTPD Service 
    service: name=httpd state=started enabled=True 
    when: ansible_os_family == "RedHat" 

  - name: Disable Firewall Service 
    service: name=ufw state=stopped enabled=False
    when: ansible_os_family == "Debian" 

  - name: Disable FirewallD Service 
    service: name=firewalld state=stopped enabled=False
    when: ansible_os_family == "RedHat" 

  - name: Deploy Custom Index Page
    copy: src=files/index.html dest=/var/www/html/index.html
